name: Deploy Gitee Pages

on:
  deployment:

  workflow_dispatch:

jobs:
  deploy-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        run: |
          git push --force https://dontcampy:${{ secrets.GITEE_PAT }}@gitee.com/sagi-mura/button.git  gh-pages:master
